#!/bin/bash

# active the python venv if is not active already.
if [[ -z $VIRTUAL_ENV ]]; then
    source .env/bin/activate
fi

clear

case $1 in
run)
    DEBUG=1 uvicorn main:app --reload --port 7200 --use-colors
    ;;

red)
    redis-server config/redis.conf
    ;;

update_db)
    alembic -c config/alembic.ini revision --autogenerate
    alembic -c config/alembic.ini upgrade head
    ;;

master)
    sqlite3 $2 "UPDATE users SET admin = '1' WHERE user_id = $3"
    ;;

release)
    if [[ -z $2 ]]; then
        exit
    else
        echo $2 > VERSION
        if [[ -z $(git diff --name-only VERSION) ]]; then
            echo -e "\n----------\nNo Change\n----------"
            exit 1
        fi

        git add VERSION
        git commit -m "release: $2"
    fi
    ;;

delete_all_tags)
    echo "Not Now"
    # git tag | grep <pattern> | xargs -n 1 -i% git push origin :refs/tags/%
    # git tag | xargs -n 1 -i% sh -c 'git push origin :% && git tag -d %'
    ;;
esac
