// DO NOT EDIT THIS FILE.
// THIS IS A GENERATED FILE AND ANY EDIT WILL BE REPLACED
import * as ud from './user_defined';
export const API_VERSION = '0.1.42';


export type ProductUpdateBody = { description:(string),count:(number),price:(number),detail:(string),tag_bed?:(((number) | null)),code:(string),slug:(string),name:(string),best:(boolean),tag_leg?:(((number) | null)),specification:({  }), };
export type VerificationResponse = { expires:(number),action:Action, };
export type ProductTag = { name:(string),count:(number),kind:ProductKind,part:ProductPart,id:(number), };
export type ProductAddBody = { slug:(string),code:(string),kind:ProductKind,name:(string), };
export type AdminUserUpdateBody = { name?:(((string) | null)),perms?:(((((number)[])) | null)),banned:(boolean), };
export type MaterialPhoto = { photo:(File), };
export type ProductPhoto = { photo:(File), };
export type ErrorCode = "unknown"|"forbidden"|"forbidden_self_edit"|"bad_auth"|"not_found"|"not_unique"|"server_error"|"database_error"|"rate_limited"|"index_out_of_bounds"|"bad_image"|"encode_webp_error"|"user_banned"|"bad_phone"|"bad_slug_len"|"bad_slug_abc"|"bad_verification"|"string_too_long"|"too_many_photos";
export const ERROR_CODE = ["unknown","forbidden","forbidden_self_edit","bad_auth","not_found","not_unique","server_error","database_error","rate_limited","index_out_of_bounds","bad_image","encode_webp_error","user_banned","bad_phone","bad_slug_len","bad_slug_abc","bad_verification","string_too_long","too_many_photos",] as const;
export function is_error_code(value: string): value is ErrorCode {
    return ERROR_CODE.includes(value as ErrorCode)
}
;
export type ProductTagUpdateBody = { name:(string), };
export type LoginBody = { phone:(string),code:(string), };
export type AppErr = { code:ErrorCode,debug?:(((string) | null)),status:(number), };
export type OrderList = { users:((User[])),orders:((Order[])), };
export type Material = { created_at:(number),updated_at:(number),name:(string),created_by?:(((number) | null)),detail:(string),updated_by?:(((number) | null)),count:(number),photo?:(((string) | null)),id:(number), };
export type UserUpdateBody = { name?:(((string) | null)), };
export type Order = { product:(number),count:(number),updated_at:(number),user:(number),id:(number),created_at:(number),state:OrderState,price:(number), };
export type ProductPart = "leg"|"bed";
export const PRODUCT_PART = ["leg","bed",] as const;
export function is_product_part(value: string): value is ProductPart {
    return PRODUCT_PART.includes(value as ProductPart)
}
;
export type ProductKind = "chair"|"table";
export const PRODUCT_KIND = ["chair","table",] as const;
export function is_product_kind(value: string): value is ProductKind {
    return PRODUCT_KIND.includes(value as ProductKind)
}
;
export type MaterialAddBody = { detail:(string),count:(number),name:(string), };
export type User = { banned:(boolean),created_at:(number),order_count:(number),photo?:(((string) | null)),token?:(((string) | null)),name?:(((string) | null)),online_at:(number),admin:(((number)[])),phone:(string),id:(number), };
export type Action = "login"|"delete";
export const ACTION = ["login","delete",] as const;
export function is_action(value: string): value is Action {
    return ACTION.includes(value as Action)
}
;
export type MaterialUpdateInfoBody = { name:(string),detail:(string), };
export type UserAddOrderBody = { count:(number),product:(number), };
export type MaterialList = { users:((User[])),materials:((Material[])), };
export type ProductTagAddBody = { kind:ProductKind,name:(string),part:ProductPart, };
export type MaterialUpdateCountBody = { count:(number), };
export type UpdatePhoto = { photo:(File), };
export type OrderUpdateBody = { state:OrderState, };
export type Product = { tag_leg?:(((number) | null)),kind:ProductKind,description:(string),count:(number),name:(string),best:(boolean),price:(number),code:(string),id:(number),tag_bed?:(((number) | null)),slug:(string),updated_at:(number),thumbnail?:(((string) | null)),photos:(((string)[])),specification:({  }),created_at:(number),detail:(string), };
export type VerificationData = { action:Action,phone:(string), };
export type OrderState = "pending"|"rejected"|"resolved";
export const ORDER_STATE = ["pending","rejected","resolved",] as const;
export function is_order_state(value: string): value is OrderState {
    return ORDER_STATE.includes(value as OrderState)
}
;
/**
List

*/
export async function api_admin_product_tags_list (params: {page:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<((ProductTag[]))>> {
    let { page } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/product-tags/`,
        method: 'GET',
        params: { page },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<((ProductTag[]))> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<((ProductTag[]))>

}
/**
Product Delete

*/
export async function api_admin_products_del (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Update

*/
export async function api_user_patch (body: UserUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/user/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Product List

*/
export async function api_admin_products_list (params: {page:(number),best?:(((boolean) | null)),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<((Product[]))>> {
    let { page,best } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/`,
        method: 'GET',
        params: { page,best },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<((Product[]))> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<((Product[]))>

}
/**
Get

*/
export async function api_admin_users_get (params: {uid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    let { uid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/users/${uid}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Set Thumbnail

*/
export async function api_admin_products_thumbnail_put (params: {id:(number),}, body: ProductPhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/admin/products/${id}/thumbnail/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Add

*/
export async function api_admin_products_post (body: ProductAddBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/products/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Add Photo

*/
export async function api_admin_products_photos_put (params: {id:(number),}, body: ProductPhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/admin/products/${id}/photos/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
List

*/
export async function api_admin_materials_get (params: {page:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<MaterialList>> {
    let { page } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/materials/`,
        method: 'GET',
        params: { page },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<MaterialList> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<MaterialList>

}
/**
Update

*/
export async function api_admin_product_tags_patch (params: {id:(number),}, body: ProductTagUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<ProductTag>> {
    let { id } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/product-tags/${id}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<ProductTag> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<ProductTag>

}
/**
Del Photo

*/
export async function api_admin_materials_photo_del (params: {mid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/photo/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Delete Photo

*/
export async function api_admin_products_photos_del (params: {id:(number),idx:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { id,idx } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/photos/${idx}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Update Photo

*/
export async function api_user_photo_put (body: UpdatePhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/user/photo/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Get

*/
export async function api_admin_product_tags_get (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<ProductTag>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/product-tags/${id}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<ProductTag> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<ProductTag>

}
/**
Delete Thumbnail

*/
export async function api_admin_products_thumbnail_del (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/thumbnail/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Get

*/
export async function api_admin_orders_get (params: {oid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Order>> {
    let { oid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/orders/${oid}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Order> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Order>

}
/**
Update

*/
export async function api_admin_orders_patch (params: {oid:(number),}, body: OrderUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Order>> {
    let { oid } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/orders/${oid}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Order> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Order>

}
/**
Update Info

*/
export async function api_admin_materials_info_patch (params: {mid:(number),}, body: MaterialUpdateInfoBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/info/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Update Count

*/
export async function api_admin_materials_count_patch (params: {mid:(number),}, body: MaterialUpdateCountBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/count/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
List

*/
export async function api_admin_users_list (params: {page:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<((User[]))>> {
    let { page } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/users/`,
        method: 'GET',
        params: { page },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<((User[]))> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<((User[]))>

}
/**
Get

*/
export async function api_user_get (override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/user/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Product Get

*/
export async function api_admin_products_get (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Verification

*/
export async function api_verification_post (body: VerificationData, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<VerificationResponse>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/verification/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<VerificationResponse> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<VerificationResponse>

}
/**
Delete

*/
export async function api_admin_materials_del (params: {mid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { mid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Add

*/
export async function api_admin_materials_post (body: MaterialAddBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/materials/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Add

*/
export async function api_admin_product_tags_post (body: ProductTagAddBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<ProductTag>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/product-tags/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<ProductTag> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<ProductTag>

}
/**
Delete

*/
export async function api_admin_product_tags_del (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/product-tags/${id}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Delete

*/
export async function api_admin_orders_del (params: {oid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { oid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/orders/${oid}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Set Photo

*/
export async function api_admin_materials_photo_put (params: {mid:(number),}, body: MaterialPhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/photo/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Update

*/
export async function api_admin_products_patch (params: {id:(number),}, body: ProductUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Update

*/
export async function api_admin_users_patch (params: {id:(number),}, body: AdminUserUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    let { id } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/users/${id}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Delete Photo

*/
export async function api_user_photo_del (override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/user/photo/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Logout

*/
export async function api_user_logout_post (override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/user/logout/`,
        method: 'POST',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Login

*/
export async function api_user_login_post (body: LoginBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/user/login/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Add

*/
export async function api_orders_post (body: UserAddOrderBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Order>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/orders/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Order> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Order>

}
