// DO NOT EDIT THIS FILE.
// THIS IS A GENERATED FILE AND ANY EDIT WILL BE REPLACED
import * as ud from './user_defined';
export const API_VERSION = '0.1.42';


export type OrderState = "pending"|"rejected"|"resolved";
export const ORDER_STATE = ["pending","rejected","resolved",] as const;
export function is_order_state(value: string): value is OrderState {
    return ORDER_STATE.includes(value as OrderState)
}
;
export type UserUpdateBody = { name?:(((string) | null)), };
export type VerificationData = { action:Action,phone:(string), };
export type ProductUpdateBody = { best:(boolean),code:(string),count:(number),detail:(string),tag_bed?:(((number) | null)),price:(number),name:(string),tag_leg?:(((number) | null)),description:(string),specification:({  }),slug:(string), };
export type AppErr = { status:(number),code:ErrorCode,debug?:(((string) | null)), };
export type Product = { kind:ProductKind,code:(string),created_at:(number),name:(string),tag_bed?:(((number) | null)),thumbnail?:(((string) | null)),specification:({  }),description:(string),best:(boolean),slug:(string),price:(number),count:(number),detail:(string),id:(number),tag_leg?:(((number) | null)),photos:(((string)[])),updated_at:(number), };
export type Order = { id:(number),price:(number),count:(number),updated_at:(number),product:(number),user:(number),created_at:(number),state:OrderState, };
export type ProductAddBody = { name:(string),kind:ProductKind,slug:(string),code:(string), };
export type MaterialAddBody = { detail:(string),count:(number),name:(string), };
export type ProductPart = "leg"|"bed";
export const PRODUCT_PART = ["leg","bed",] as const;
export function is_product_part(value: string): value is ProductPart {
    return PRODUCT_PART.includes(value as ProductPart)
}
;
export type UpdatePhoto = { photo:(File), };
export type ProductPhoto = { photo:(File), };
export type Action = "login"|"delete";
export const ACTION = ["login","delete",] as const;
export function is_action(value: string): value is Action {
    return ACTION.includes(value as Action)
}
;
export type MaterialList = { materials:((Material[])),users:((User[])), };
export type ErrorCode = "unknown"|"forbidden"|"bad_auth"|"not_found"|"not_unique"|"server_error"|"database_error"|"rate_limited"|"index_out_of_bounds"|"bad_image"|"encode_webp_error"|"user_banned"|"bad_phone"|"bad_slug_len"|"bad_slug_abc"|"bad_verification"|"too_many_photos"|"count_min";
export const ERROR_CODE = ["unknown","forbidden","bad_auth","not_found","not_unique","server_error","database_error","rate_limited","index_out_of_bounds","bad_image","encode_webp_error","user_banned","bad_phone","bad_slug_len","bad_slug_abc","bad_verification","too_many_photos","count_min",] as const;
export function is_error_code(value: string): value is ErrorCode {
    return ERROR_CODE.includes(value as ErrorCode)
}
;
export type AdminUserUpdateBody = { perms?:(((((number)[])) | null)),banned:(boolean),name?:(((string) | null)), };
export type ProductTagAddBody = { name:(string),kind:ProductKind,part:ProductPart, };
export type MaterialPhoto = { photo:(File), };
export type Material = { created_by?:(((number) | null)),id:(number),detail:(string),created_at:(number),photo?:(((string) | null)),count:(number),updated_at:(number),updated_by?:(((number) | null)),name:(string), };
export type MaterialUpdateInfoBody = { detail:(string),name:(string), };
export type VerificationResponse = { action:Action,expires:(number), };
export type ProductKind = "chair"|"table";
export const PRODUCT_KIND = ["chair","table",] as const;
export function is_product_kind(value: string): value is ProductKind {
    return PRODUCT_KIND.includes(value as ProductKind)
}
;
export type ProductTagUpdateBody = { name:(string), };
export type UserAddOrderBody = { product:(number),count:(number), };
export type MaterialUpdateCountBody = { count:(number), };
export type User = { order_count:(number),admin:(((number)[])),photo?:(((string) | null)),banned:(boolean),id:(number),name?:(((string) | null)),online_at:(number),phone:(string),token?:(((string) | null)),created_at:(number), };
export type ProductTag = { count:(number),id:(number),kind:ProductKind,name:(string),part:ProductPart, };
export type LoginBody = { code:(string),phone:(string), };
export type OrderUpdateBody = { state:OrderState, };
/**
Update

*/
export async function api_admin_users_patch (params: {id:(number),}, body: AdminUserUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    let { id } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/users/${id}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
List

*/
export async function api_admin_users_list (params: {page:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<((User[]))>> {
    let { page } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/users/`,
        method: 'GET',
        params: { page },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<((User[]))> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<((User[]))>

}
/**
Get

*/
export async function api_admin_product_tags_get (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<ProductTag>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/product-tags/${id}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<ProductTag> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<ProductTag>

}
/**
Get

*/
export async function api_admin_orders_get (params: {oid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Order>> {
    let { oid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/orders/${oid}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Order> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Order>

}
/**
Del Photo

*/
export async function api_admin_materials_photo_del (params: {mid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/photo/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Product Delete

*/
export async function api_admin_products_del (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Verification

*/
export async function api_verification_post (body: VerificationData, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<VerificationResponse>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/verification/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<VerificationResponse> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<VerificationResponse>

}
/**
List

*/
export async function api_admin_product_tags_list (params: {page:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<((ProductTag[]))>> {
    let { page } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/product-tags/`,
        method: 'GET',
        params: { page },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<((ProductTag[]))> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<((ProductTag[]))>

}
/**
Update Count

*/
export async function api_admin_materials_count_patch (params: {mid:(number),}, body: MaterialUpdateCountBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/count/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Set Photo

*/
export async function api_admin_materials_photo_put (params: {mid:(number),}, body: MaterialPhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/photo/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
List

*/
export async function api_admin_materials_get (params: {page:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<MaterialList>> {
    let { page } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/materials/`,
        method: 'GET',
        params: { page },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<MaterialList> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<MaterialList>

}
/**
List

*/
export async function api_admin_orders_list (params: {page:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<((([ ({ updated_at:(number),product:(number),user:(number),state:OrderState,id:(number),created_at:(number),count:(number),price:(number), }),((({ created_at:(number),online_at:(number),order_count:(number),photo?:(((string) | null)),token?:(((string) | null)),name?:(((string) | null)),banned:(boolean),id:(number),admin:(((number)[])),phone:(string), }) | null)), ])[]))>> {
    let { page } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/orders/`,
        method: 'GET',
        params: { page },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<((([ ({ updated_at:(number),product:(number),user:(number),state:OrderState,id:(number),created_at:(number),count:(number),price:(number), }),((({ created_at:(number),online_at:(number),order_count:(number),photo?:(((string) | null)),token?:(((string) | null)),name?:(((string) | null)),banned:(boolean),id:(number),admin:(((number)[])),phone:(string), }) | null)), ])[]))> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<((([ ({ updated_at:(number),product:(number),user:(number),state:OrderState,id:(number),created_at:(number),count:(number),price:(number), }),((({ created_at:(number),online_at:(number),order_count:(number),photo?:(((string) | null)),token?:(((string) | null)),name?:(((string) | null)),banned:(boolean),id:(number),admin:(((number)[])),phone:(string), }) | null)), ])[]))>

}
/**
Delete Photo

*/
export async function api_admin_products_photos_del (params: {id:(number),idx:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { id,idx } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/photos/${idx}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Add

*/
export async function api_admin_products_post (body: ProductAddBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/products/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Update

*/
export async function api_admin_products_patch (params: {id:(number),}, body: ProductUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Update Info

*/
export async function api_admin_materials_info_patch (params: {mid:(number),}, body: MaterialUpdateInfoBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    let { mid } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/info/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Add

*/
export async function api_orders_post (body: UserAddOrderBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Order>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/orders/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Order> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Order>

}
/**
Update

*/
export async function api_user_patch (body: UserUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/user/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Delete

*/
export async function api_admin_materials_del (params: {mid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { mid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/materials/${mid}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Add

*/
export async function api_admin_product_tags_post (body: ProductTagAddBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<ProductTag>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/product-tags/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<ProductTag> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<ProductTag>

}
/**
Product Get

*/
export async function api_admin_products_get (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Update Photo

*/
export async function api_user_photo_put (body: UpdatePhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/user/photo/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Get

*/
export async function api_admin_users_get (params: {uid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    let { uid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/users/${uid}/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Delete

*/
export async function api_admin_orders_del (params: {oid:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { oid } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/orders/${oid}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Update

*/
export async function api_admin_orders_patch (params: {oid:(number),}, body: OrderUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Order>> {
    let { oid } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/orders/${oid}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Order> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Order>

}
/**
Delete

*/
export async function api_admin_product_tags_del (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/product-tags/${id}/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Product List

*/
export async function api_admin_products_list (params: {page:(number),best?:(((boolean) | null)),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<((Product[]))>> {
    let { page,best } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/`,
        method: 'GET',
        params: { page,best },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<((Product[]))> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<((Product[]))>

}
/**
Get

*/
export async function api_user_get (override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/user/`,
        method: 'GET',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Add

*/
export async function api_admin_materials_post (body: MaterialAddBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Material>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/materials/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Material> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Material>

}
/**
Logout

*/
export async function api_user_logout_post (override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/user/logout/`,
        method: 'POST',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Update

*/
export async function api_admin_product_tags_patch (params: {id:(number),}, body: ProductTagUpdateBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<ProductTag>> {
    let { id } = params;
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/admin/product-tags/${id}/`,
        method: 'PATCH',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<ProductTag> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<ProductTag>

}
/**
Delete Photo

*/
export async function api_user_photo_del (override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<void>> {
    
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/user/photo/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: void 0 as void,
        ok(): this is ud.Ok<void> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<void>

}
/**
Delete Thumbnail

*/
export async function api_admin_products_thumbnail_del (params: {id:(number),}, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = void 0;
    let r = await ud.httpx({
        url: `/api/admin/products/${id}/thumbnail/`,
        method: 'DELETE',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Login

*/
export async function api_user_login_post (body: LoginBody, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<User>> {
    
    let data = JSON.stringify(body);
    let r = await ud.httpx({
        url: `/api/user/login/`,
        method: 'POST',
        params: {  },
        headers: { 'Content-Type': 'application/json', },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<User> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<User>

}
/**
Set Thumbnail

*/
export async function api_admin_products_thumbnail_put (params: {id:(number),}, body: ProductPhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/admin/products/${id}/thumbnail/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
/**
Add Photo

*/
export async function api_admin_products_photos_put (params: {id:(number),}, body: ProductPhoto, override: Partial<ud.HttpxProps> = {}) : Promise<ud.Result<Product>> {
    let { id } = params;
    let data = new FormData();
data.set('photo', body.photo);

    let r = await ud.httpx({
        url: `/api/admin/products/${id}/photos/`,
        method: 'PUT',
        params: {  },
        headers: {  },
        data, ...override
    })

    return {
        r: r.clone(),
        status: r.status,
        body: await r.json(),
        ok(): this is ud.Ok<Product> {
            return this.status == 200
        },
        err(): this is ud.Err {
            return !this.ok()
        },
    } as ud.Result<Product>

}
